# Generated by Django 4.2 on 2025-04-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('father_name', models.CharField(blank=True, max_length=25, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('passport_series', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=50, null=True)),
                ('live_address', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='account/student/profile_photo/%Y/%m/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
