# Generated by Django 4.2 on 2025-05-17 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='indebtedness',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='paid',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salary', models.PositiveBigIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='account.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
