# Generated by Django 4.2 on 2025-04-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passport_series',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
