# Generated by Django 4.2 on 2025-05-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_employee_date_of_joined_employee_indebtedness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='indebtedness',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
