# Generated by Django 4.2 on 2025-05-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_employee_indebtedness_remove_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_left',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_left',
            field=models.BooleanField(default=False),
        ),
    ]
