# Generated by Django 4.2 on 2025-05-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_employee_date_of_left_employee_is_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('boss', 'boss'), ('employee', 'employee')], default='employee', max_length=250),
        ),
    ]
