# Generated by Django 4.2 on 2025-04-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_first_name_student_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contract_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course_price',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
