# Generated by Django 4.2 on 2025-06-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('boss', 'boss'), ('employee', 'employee'), ('service', 'service')], default='employee', max_length=250),
        ),
    ]
