# Generated by Django 4.2 on 2025-04-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_student_contract_number_student_course_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='debt',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_debt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='paid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
