# Generated by Django 4.2 on 2025-04-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_payment_payment_id_alter_payment_payment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
