# Generated by Django 4.2 on 2025-04-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
