# Generated by Django 4.2 on 2025-04-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_student_phone_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('phone_number', 'full_name', 'card_number')},
        ),
    ]
