# Generated by Django 4.2 on 2025-04-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_student_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
