# Generated by Django 4.2 on 2025-04-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_student_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('naxt', 'naxt'), ('click', 'click'), ('alif_bank', 'alif_bank'), ('uzum_bank', 'uzum_bank'), ('hisob_raqam', 'hisob_raqam'), ('zoodpay', 'zoodpay'), ('visa', 'visa'), ('anor_bank', 'anor_bank')], default='naxt', max_length=250),
        ),
    ]
