# Generated by Django 4.2 on 2025-04-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_type',
            field=models.CharField(choices=[('naqd', 'naqd'), ('nasya', 'nasya'), ('karta', 'karta')], default='naqd', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='tariff',
            field=models.CharField(choices=[('premium', 'premium'), ('vip', 'vip'), ('biznes', 'biznes')], default='vip', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('naqd', 'naqd'), ('click', 'click'), ('alif_bank', 'alif_bank'), ('uzum_bank', 'uzum_bank'), ('hisob_raqam', 'hisob_raqam'), ('zoodpay', 'zoodpay'), ('visa', 'visa'), ('anor_bank', 'anor_bank')], default='naxt', max_length=250),
        ),
    ]
