# Generated by Django 4.2 on 2025-05-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_student_payment_type_student_tariff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group_joined',
            field=models.BooleanField(default=False),
        ),
    ]
