# Generated by Django 4.2 on 2025-05-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_student_group_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('cash', 'cash'), ('card', 'card'), ('credit', 'credit')], default='naxt', max_length=250),
        ),
    ]
