# Generated by Django 4.2 on 2025-05-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank',
            field=models.CharField(blank=True, choices=[('uzum', 'uzum'), ('alif', 'alif'), ('anor', 'anor'), ('zoodpay', 'zoodpay'), ('click', 'click'), ('payme', 'payme')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('cash', 'cash'), ('card', 'card'), ('credit', 'credit')], default='cash', max_length=50),
        ),
    ]
