# Generated by Django 4.2 on 2025-05-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_debt',
            field=models.BooleanField(default=True),
        ),
    ]
