# Generated by Django 4.2 on 2025-05-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_time', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(choices=[('cash', 'cash'), ('card', 'card'), ('credit', 'credit')], default='cash', max_length=50)),
                ('bank', models.CharField(blank=True, choices=[('cash_uzs', 'cash_uzs'), ('cash_usd', 'cash_usd'), ('account_number', 'account_number'), ('alif', 'alif'), ('anor', 'anor'), ('uzum', 'uzum'), ('P2P', 'P2P'), ('other', 'other'), ('payme', 'payme'), ('click', 'click')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('total_price', models.PositiveBigIntegerField(default=0)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='account/student/profile_photo/%Y/%m/')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('group_id', models.CharField(blank=True, max_length=250, null=True)),
                ('telegram_link', models.CharField(blank=True, max_length=200, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=250, null=True)),
                ('course_price', models.PositiveBigIntegerField(default=10000000)),
                ('paid', models.IntegerField(blank=True, null=True)),
                ('debt', models.IntegerField(blank=True, null=True)),
                ('is_debt', models.BooleanField(default=True)),
                ('tariff', models.CharField(choices=[('premium', 'premium'), ('vip', 'vip'), ('biznes', 'biznes')], max_length=50)),
                ('payment_type', models.CharField(choices=[('naqd', 'naqd'), ('nasya', 'nasya'), ('karta', 'karta')], max_length=15)),
                ('group_joined', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('phone_number', 'full_name', 'card_number')},
            },
        ),
        migrations.CreateModel(
            name='PaymentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='account/payment/%Y/%m/')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='student.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='student.student'),
        ),
    ]
