# Generated by Django 4.2 on 2025-05-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('prepayment', 'prepayment'), ('partially', 'partially'), ('completed', 'completed')], default='prepayment', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_id_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_price',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.RemoveField(
            model_name='student',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_price',
        ),
    ]
