# Generated by Django 4.2 on 2025-05-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_unique_together_student_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='student',
            name='suprice',
            field=models.BooleanField(default=False),
        ),
    ]
