# Generated by Django 4.2 on 2025-05-10 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('student', '0003_remove_student_profile_photo_student_suprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='account.employee'),
        ),
    ]
