# Generated by Django 4.2 on 2025-05-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='payment_type',
        ),
    ]
