# Generated by Django 4.2 on 2025-05-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_time',
            field=models.DateField(null=True),
        ),
    ]
