# Generated by Django 4.2 on 2025-05-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_payment_payment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
