# Generated by Django 4.2 on 2025-05-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='month',
            field=models.CharField(choices=[('yanvar', 'yanvar'), ('fevral', 'fevral'), ('mart', 'mart'), ('aprel', 'aprel'), ('may', 'may'), ('iyun', 'iyun'), ('iyul', 'iyul'), ('avgust', 'avgust'), ('sentabr', 'sentabr'), ('oktabr', 'oktabr'), ('noyabr', 'noyabr'), ('dekabr', 'dekabr')], default='aprel', max_length=50),
        ),
    ]
