# Generated by Django 4.2 on 2025-06-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_studentdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='StudentDescription',
        ),
    ]
