# Generated by Django 4.2 on 2025-06-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_notification_delete_studentdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram_full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
