# Generated by Django 4.2 on 2025-06-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_notification_contract_number_notification_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_blacklist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='type',
            field=models.CharField(choices=[('new', 'new'), ('study', 'study'), ('graduate', 'graduate')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('group_name', models.CharField(max_length=250)),
                ('start_date_online', models.DateField()),
                ('start_date_offline', models.DateField()),
                ('students', models.ManyToManyField(related_name='groups', to='student.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
