# Generated by Django 4.2 on 2025-06-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_student_is_blacklist_student_type_studentgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='telegram_link',
        ),
    ]
