# Generated by Django 4.2 on 2025-06-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_telegramgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroup',
            name='group_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
