# Generated by Django 4.2 on 2025-06-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_telegramgroup_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='students',
            field=models.ManyToManyField(related_name='telegram_groups', to='student.student'),
        ),
    ]
