# Generated by Django 4.2 on 2025-07-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_studentmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='study_type',
            field=models.CharField(choices=[('offline', 'offline'), ('online', 'online')], default='offline', max_length=10),
        ),
    ]
