# Generated by Django 4.2 on 2025-07-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_student_study_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='student_group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
