# Generated by Django 4.2 on 2025-07-27 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=250, null=True)),
                ('phone_number', models.CharField(max_length=250, null=True)),
                ('contract_number', models.CharField(max_length=250, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_time', models.DateField(null=True)),
                ('price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(choices=[('cash', 'cash'), ('card', 'card'), ('credit', 'credit')], default='cash', max_length=50)),
                ('bank', models.CharField(blank=True, choices=[('cash_uzs', 'cash_uzs'), ('cash_usd', 'cash_usd'), ('account_number', 'account_number'), ('alif', 'alif'), ('anor', 'anor'), ('uzum', 'uzum'), ('P2P', 'P2P'), ('other', 'other'), ('payme', 'payme'), ('click', 'click')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('student_id_time', models.DateField(blank=True, null=True)),
                ('student_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=250, null=True)),
                ('course_price', models.PositiveBigIntegerField()),
                ('paid', models.IntegerField(blank=True, null=True)),
                ('debt', models.IntegerField(blank=True, null=True)),
                ('is_debt', models.BooleanField(default=True)),
                ('tariff', models.CharField(choices=[('premium', 'premium'), ('vip', 'vip'), ('biznes', 'biznes')], max_length=50)),
                ('status', models.CharField(choices=[('prepayment', 'prepayment'), ('partially', 'partially'), ('completed', 'completed')], max_length=25)),
                ('type', models.CharField(choices=[('new', 'new'), ('study', 'study'), ('graduate', 'graduate')], default='new', max_length=20)),
                ('study_type', models.CharField(choices=[('offline', 'offline'), ('online', 'online')], default='offline', max_length=10)),
                ('is_blacklist', models.BooleanField(default=False)),
                ('group_joined', models.BooleanField(default=False)),
                ('suprice', models.BooleanField(default=False)),
                ('month', models.CharField(choices=[('yanvar', 'yanvar'), ('fevral', 'fevral'), ('mart', 'mart'), ('aprel', 'aprel'), ('may', 'may'), ('iyun', 'iyun'), ('iyul', 'iyul'), ('avgust', 'avgust'), ('sentabr', 'sentabr'), ('oktabr', 'oktabr'), ('noyabr', 'noyabr'), ('dekabr', 'dekabr')], default='aprel', max_length=50)),
                ('telegram_id', models.CharField(blank=True, max_length=250, null=True)),
                ('telegram_full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=250, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='account.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('group_id', models.BigIntegerField(unique=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('students', models.ManyToManyField(related_name='telegram_groups', to='student.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=500)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='student.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('group_name', models.CharField(max_length=250)),
                ('start_date_online', models.DateField()),
                ('start_date_offline', models.DateField()),
                ('students', models.ManyToManyField(related_name='groups', to='student.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='account/payment/%Y/%m/')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='student.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='student.student'),
        ),
    ]
