# Generated by Django 4.2 on 2025-07-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
