# Generated by Django 4.2 on 2025-08-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_studentgroup_students_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='student_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='student_start_date',
            field=models.DateField(null=True),
        ),
    ]
